In [13]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
from numpy import random
from collections import Counter
from numpy.linalg import inv
from numpy.linalg import eig
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

In [81]:
df=pd.read_excel("CDAC_DataBook.xlsx",sheet_name="faithful")

# 1 Sample z test / ttest

In [3]:
erupt=df["eruptions"]

In [8]:
xbar=np.mean(erupt)
xbar

np.float64(3.4877830882352936)

In [10]:
n=len(erupt)
n

272

In [12]:
sd=np.std(erupt,ddof=1)
sd

1.1413712511052077

In [45]:
ssw.ztest(erupt,value=3.7,alternative="smaller") # output will (test_statistics , p-value)

(np.float64(-3.06646147570652), np.float64(0.0010830435959524984))

In [42]:
# calculating the Test Statistics
ts=(xbar-3.7)/(sd/n**0.5)
ts

np.float64(-3.066461475706521)

In [35]:
zc=norm.ppf(0.05)
zc

np.float64(-1.6448536269514729)

Ho: u<=3.53

Ha: u>3.53

In [52]:
ts=(xbar-3.53)/(sd/n**0.5)   # test statistics calculated for 3.53
ts

np.float64(-0.6100198729369253)

In [53]:
norm.cdf(ts) # calculated p value for u=3.53

np.float64(0.2709243216144542)

In [51]:
ssw.ztest(erupt,value=3.53,alternative="smaller")

(np.float64(-0.6100198729369251), np.float64(0.27092432161445423))

np.float64(0.2709243216144542)

u will not exceeed 3.37

Ho: u<=3.37

Ha: u>3.7

In [54]:
ts=(xbar-3.37)/(sd/n**0.5)   # test statistics calculated for 3.53
ts

np.float64(1.7019251649638614)

In [59]:
1-norm.cdf(ts)

np.float64(0.044384698843295656)

In [58]:
Zc=norm.ppf(0.95) #Zc
Zc

np.float64(1.6448536269514722)

In [60]:
ssw.ztest(erupt,value=3.37,alternative="larger")

(np.float64(1.7019251649638607), np.float64(0.044384698843295746))

Waiting

In [63]:
wait=erupt=df["waiting"]

In [64]:
xbar= np.mean(wait)
sd=np.std(wait)
n=len(wait)

In [65]:
ts=(xbar-75)/(sd/n**0.5)
ts

np.float64(-4.986561441407454)

In [73]:
z=norm.cdf(ts)
z

np.float64(3.0731683147713225e-07)

In [69]:
Zc=norm.ppf(0.05)
Zc

np.float64(-1.6448536269514729)

In [71]:
ssw.ztest(wait,value=75,alternative="smaller")

(np.float64(-4.9773865275793225), np.float64(3.222427049500608e-07))

In [78]:
ub=xbar+1.645*(sd/n**0.5)
ub

np.float64(72.25056430312681)

In [80]:
xbar

np.float64(70.8970588235294)

# 2 Sample t test

In [107]:
df=pd.read_excel("CDAC_DataBook.xlsx",sheet_name="faithful")

In [108]:
df.head()

   eruptions  waiting
0      3.600       79
1      1.800       54
2      3.333       74
3      2.283       62
4      4.533       85

In [109]:
df1=df.iloc[20:60]
df2=df.iloc[120:170]

In [110]:
erupt1=df1.eruptions
erupt2=df2.eruptions

In [111]:
np.mean(erupt1),np.mean(erupt2)

(np.float64(3.44745), np.float64(3.4876399999999994))

In [112]:
#mean of Errupt 2 is atleast 0.12 more than measn of errupt1

# Ho: mean(E2)-mean(E1)>=0.12
# Ha:  mean(E2)-mean(E1)<0.12

In [113]:
ssw.ztest(erupt2,erupt1,value=0.12,alternative="smaller")

(np.float64(-0.3196536558502502), np.float64(0.3746154475542464))

In [115]:
ssw.ztest(erupt2,erupt1,value=0,alternative="two-sided")

(np.float64(0.160968305082337), np.float64(0.8721183639481939))

In [116]:
0.87>0.05

True

Travel in Blore is atleast 15 min more than Mumbai

Blore
Sample size 50
Avg time 45
Std Dev 10.5

Mumbai
Sample size 60
Avg time 34
Std Dev 5.6

In [117]:
(45-34)-15/((10.5**2/50)+(5.6**2/60))**0.5

1.9177048575604498

In [120]:

norm.ppf(0.318)

np.float64(-0.47329882543243695)

In [122]:
df=pd.read_csv("6-Churn_ModellingDataSet.csv")

In [123]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [124]:
ssw.ztest(df.Age,df.Exited,value=0,alternative="two-sided")

(np.float64(368.90059346979893), np.float64(0.0))

In [125]:
a1=df.Age[np.where(df.Exited==0)[0]]
a2=df.Age[np.where(df.Exited==1)[0]]

In [126]:

ssw.ztest(a1,a2,value=0,alternative="two-sided")

(np.float64(-29.76681499437077), np.float64(1.0508082506224645e-194))